### ISSUE TITLE
some confusion about trainning details

### ISSUE THREAD

**Issue by deep-practice** [ShiqiYu/libfacedetection.train#1]
1.why set rgb_mean=(0,0,0) 
2.why start trainning landmarks unitl 100 epoch later?
3.why trainning landmarks in every 2 epochs after 100 epoch?

**Comment by deep-practice** [comment]
No landmark branch in YuFaceDetectNet?

**Comment by ShiqiYu** [comment]
1. Because the input blob to libfacedetection is a UINT8 blob. All input to conv layers are UINT8, so I can use the SIMD for UINT8*INT* in AVX2.

2. Train a usable face detection model (without landmark detection) first.

3. the faces with landmarks in the training set are larger ones. I don't want the model cannot handle small faces.

**Comment by ShiqiYu** [comment]
->the SIMD for UINT8 x INT8 in AVX2

**Comment by deep-practice** [comment]
I see.Thx.
