### ISSUE TITLE
How to train with custom dataset by using the pretrained model?

### ISSUE THREAD

**Issue by SwEngine** [ShiqiYu/libfacedetection.train#74]
Hello,
I would like to ask a few questions about this github repo.
1. What do I need to do to train using the pretrained model?
2. How can I create my own custom dataset other than Wider-Face? Is there an annotation tool you recommend that does annotation in the same format?
3. What should I do to train with the dataset I created?
4. How can I convert the model to onnx after training?

**Comment by SwEngine** [comment]
In addition, could you share the most recent onnx file? Thanks in advance.

**Comment by Wwupup** [comment]
Hello@SwEngine , sorry for the late reply. Since the face detector is a super lightweight model, this project only considers training from scratch, and does not add a script to load the pre-trained model. In addition, this project is based on the [MMdetection 2.24.1](https://github.com/open-mmlab/mmdetection) framework. If you want to customize the dataset, you can refer to the MMdetection documentation.
